name: Lint & Test

on: [push, pull_request]

env:
  GO_VERSION: '^1.16'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

        - uses: actions/setup-go@v2
          with:
            go-version: ${{ env.GO_VERSION }}
        - name: Install gogenlicense
          run: go install github.com/tkw1536/gogenlicense/cmd/gogenlicense@latest
        - uses: actions/checkout@v2
        - name: Update licenses
          run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            go generate ./...
        - name: Check that 'gofmt' has been run
          run: test -z $(gofmt -l .)
        - name: Run 'go test'
          run: go test ./...
        - name: Build the 'akhttpd' executable
          run: go build ./cmd/akhttpd
