name: Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
        - name: Check that 'gofmt' has been run
          run: test -z $(gofmt -l .)
        - name: Run 'go test'
          run: go test ./...
        - name: Build the 'akhttpd' executable
          run: go build ./cmd/akhttpd
